import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const customers = sqliteTable("customers", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email"), phone: text("phone"), address: text("address"), leadSource: text("lead_source").notNull().default("Unknown"), createdAt: text("created_at").notNull() });
export const estimates = sqliteTable("estimates", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id), status: text("status").notNull().default("draft"), subtotalCents: integer("subtotal_cents").notNull(), discountCents: integer("discount_cents").notNull().default(0), appreciationDiscount: integer("appreciation_discount").notNull().default(0), additionalDiscountType: text("additional_discount_type").notNull().default("percent"), additionalDiscountValue: integer("additional_discount_value").notNull().default(0), totalCents: integer("total_cents").notNull(), depositCents: integer("deposit_cents").notNull(), scheduledAt: text("scheduled_at"), shareToken: text("share_token"), firstViewedAt: text("first_viewed_at"), acceptedAt: text("accepted_at"), signedName: text("signed_name"), signedAt: text("signed_at"), contractInitials: text("contract_initials"), photoRelease: text("photo_release"), contractVersion: text("contract_version"), createdAt: text("created_at").notNull() }, (table) => [index("idx_estimates_customer_id").on(table.customerId), index("idx_estimates_created_at").on(table.createdAt), index("idx_estimates_scheduled_at").on(table.scheduledAt), uniqueIndex("idx_estimates_share_token").on(table.shareToken)]);
export const customerNotes = sqliteTable("customer_notes", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id), body: text("body").notNull(), createdAt: text("created_at").notNull() }, (table) => [index("idx_customer_notes_customer_id").on(table.customerId)]);
export const invoices = sqliteTable("invoices", { id: text("id").primaryKey(), estimateId: text("estimate_id").notNull().references(() => estimates.id), customerId: text("customer_id").notNull().references(() => customers.id), status: text("status").notNull().default("draft"), subtotalCents: integer("subtotal_cents").notNull().default(0), discountCents: integer("discount_cents").notNull().default(0), discountType: text("discount_type").notNull().default("dollar"), discountValue: integer("discount_value").notNull().default(0), totalCents: integer("total_cents").notNull(), dueAt: text("due_at"), shareToken: text("share_token"), firstViewedAt: text("first_viewed_at"), createdAt: text("created_at").notNull() }, (table) => [index("idx_invoices_customer_id").on(table.customerId), index("idx_invoices_estimate_id").on(table.estimateId), uniqueIndex("idx_invoices_share_token").on(table.shareToken)]);
export const invoiceItems = sqliteTable("invoice_items", { id: text("id").primaryKey(), invoiceId: text("invoice_id").notNull().references(() => invoices.id, {onDelete:"cascade"}), name: text("name").notNull(), description: text("description").notNull().default(""), quantity: integer("quantity").notNull().default(1), unit: text("unit").notNull().default("job"), totalCents: integer("total_cents").notNull() }, (table)=>[index("idx_invoice_items_invoice_id").on(table.invoiceId)]);
export const invoiceRevisions = sqliteTable("invoice_revisions", { id:text("id").primaryKey(), invoiceId:text("invoice_id").notNull().references(()=>invoices.id,{onDelete:"cascade"}), subtotalCents:integer("subtotal_cents").notNull(), discountCents:integer("discount_cents").notNull().default(0), discountType:text("discount_type").notNull().default("dollar"), discountValue:integer("discount_value").notNull().default(0), totalCents:integer("total_cents").notNull(), dueAt:text("due_at"), status:text("status").notNull(), itemsJson:text("items_json").notNull(), createdAt:text("created_at").notNull() }, (table)=>[index("idx_invoice_revisions_invoice_id").on(table.invoiceId,table.createdAt)]);
export const estimateItems = sqliteTable("estimate_items", { id: text("id").primaryKey(), estimateId: text("estimate_id").notNull().references(() => estimates.id), name: text("name").notNull(), description: text("description").notNull().default(""), quantity: integer("quantity").notNull(), unit: text("unit").notNull(), totalCents: integer("total_cents").notNull() }, (table) => [index("idx_estimate_items_estimate_id").on(table.estimateId)]);
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), estimateId: text("estimate_id").notNull().references(() => estimates.id), type: text("type").notNull(), amountCents: integer("amount_cents").notNull(), status: text("status").notNull().default("pending"), providerId: text("provider_id"), createdAt: text("created_at").notNull() }, (table) => [index("idx_payments_estimate_status").on(table.estimateId, table.status)]);
export const paymentCheckoutSessions = sqliteTable("payment_checkout_sessions", { id:text("id").primaryKey(), estimateId:text("estimate_id").notNull().references(()=>estimates.id), type:text("type").notNull(), amountCents:integer("amount_cents").notNull(), status:text("status").notNull().default("open"), createdAt:text("created_at").notNull(), expiredAt:text("expired_at") }, (table)=>[index("idx_payment_checkout_sessions_estimate_status").on(table.estimateId,table.status)]);
export const paymentRefunds = sqliteTable("payment_refunds", { id:text("id").primaryKey(), paymentId:text("payment_id").notNull().references(()=>payments.id), estimateId:text("estimate_id").notNull().references(()=>estimates.id), amountCents:integer("amount_cents").notNull(), mode:text("mode").notNull(), status:text("status").notNull().default("pending"), providerRefundId:text("provider_refund_id"), note:text("note"), createdAt:text("created_at").notNull(), completedAt:text("completed_at") }, (table)=>[index("idx_payment_refunds_payment_status").on(table.paymentId,table.status),index("idx_payment_refunds_estimate_status").on(table.estimateId,table.status),uniqueIndex("idx_payment_refunds_provider").on(table.providerRefundId)]);
export const customerPhotos = sqliteTable("customer_photos", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id), category: text("category").notNull().default("property"), caption: text("caption"), filename: text("filename").notNull(), contentType: text("content_type").notNull(), sizeBytes: integer("size_bytes").notNull(), objectKey: text("object_key").notNull(), createdAt: text("created_at").notNull() }, (table) => [index("idx_customer_photos_customer_id").on(table.customerId), index("idx_customer_photos_category").on(table.customerId, table.category)]);
export const customerMessages = sqliteTable("customer_messages", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id), estimateId: text("estimate_id").references(() => estimates.id), channel: text("channel").notNull(), template: text("template").notNull(), body: text("body").notNull(), createdAt: text("created_at").notNull() }, (table) => [index("idx_customer_messages_customer_id").on(table.customerId), index("idx_customer_messages_estimate_id").on(table.estimateId)]);
// Partial unique lifecycle index is created by drizzle/0020_notification_lifecycle_unique.sql.
export const notifications = sqliteTable("notifications", { id: text("id").primaryKey(), type: text("type").notNull(), title: text("title").notNull(), body: text("body").notNull(), customerId: text("customer_id").references(() => customers.id), estimateId: text("estimate_id").references(() => estimates.id), readAt: text("read_at"), resolvedAt: text("resolved_at"), resolutionNote: text("resolution_note"), createdAt: text("created_at").notNull() }, (table) => [index("idx_notifications_created_at").on(table.createdAt), index("idx_notifications_unread").on(table.readAt, table.createdAt)]);
export const messageTemplates = sqliteTable("message_templates", { key: text("key").primaryKey(), subject: text("subject").notNull().default(""), body: text("body").notNull(), updatedAt: text("updated_at").notNull() });
export const estimateChangeRequests = sqliteTable("estimate_change_requests", { id:text("id").primaryKey(), estimateId:text("estimate_id").notNull().references(()=>estimates.id), customerId:text("customer_id").notNull().references(()=>customers.id), message:text("message").notNull(), status:text("status").notNull().default("open"), createdAt:text("created_at").notNull() },(table)=>[index("idx_change_requests_estimate").on(table.estimateId,table.status)]);
export const tasks = sqliteTable("tasks", { id:text("id").primaryKey(), title:text("title").notNull(), customerId:text("customer_id").references(()=>customers.id), estimateId:text("estimate_id").references(()=>estimates.id), dueAt:text("due_at"), status:text("status").notNull().default("open"), notes:text("notes"), createdAt:text("created_at").notNull(), completedAt:text("completed_at") },(table)=>[index("idx_tasks_status_due").on(table.status,table.dueAt)]);
export const expenses = sqliteTable("expenses", { id:text("id").primaryKey(), estimateId:text("estimate_id").references(()=>estimates.id), category:text("category").notNull(), description:text("description").notNull(), amountCents:integer("amount_cents").notNull(), incurredAt:text("incurred_at").notNull(), createdAt:text("created_at").notNull() },(table)=>[index("idx_expenses_estimate").on(table.estimateId),index("idx_expenses_incurred").on(table.incurredAt)]);
export const jobReports = sqliteTable("job_reports", { id:text("id").primaryKey(), estimateId:text("estimate_id").notNull().references(()=>estimates.id), customerId:text("customer_id").notNull().references(()=>customers.id), checklist:text("checklist").notNull(), notes:text("notes"), airflowBefore:text("airflow_before"), airflowAfter:text("airflow_after"), status:text("status").notNull().default("draft"), createdAt:text("created_at").notNull(), completedAt:text("completed_at") },(table)=>[index("idx_job_reports_estimate").on(table.estimateId)]);
export const authRateLimits = sqliteTable("auth_rate_limits", { key:text("key").primaryKey(), attempts:integer("attempts").notNull().default(0), windowStartedAt:integer("window_started_at").notNull(), blockedUntil:integer("blocked_until").notNull().default(0) });
