from pathlib import Path

# Guard only evidence-backed, governed, or user-confirmed LIVE parity behavior.
# Scrolling/smoothness is intentionally NOT asserted here; the user froze that
# area as good enough and requested no further smoothness work.
checks = {
    Path('app/layout.tsx'): [
        'statusBarStyle: "default"',
        'FIRE_DR_STRIDE_PARITY_SCRIPT_V14',
    ],
    Path('app/dashboard.tsx'): [
        'const editorRef=useRef<HTMLElement|null>(null);',
        'editorRef.current?.scrollIntoView({behavior:"smooth",block:"start"})',
        '<section ref={editorRef} className="template-editor"><header>',
        '["dashboard", "Dashboard", House]',
        '["contracts", "Contracts", PenLine]',
        '["customers", "Customers", Users]',
        '["estimates", "Estimates", ClipboardList]',
        '["followups", "Follow-ups", Clock3]',
        '["schedule", "Schedule", CalendarDays]',
        '["invoices", "Invoices", Receipt]',
        '["business", "Business", BriefcaseBusiness]',
        '["payments", "Payments", CreditCard]',
        '["settings", "Templates", Settings]',
        'className="mobile-primary-actions"',
        'aria-label="Open owner account"',
        'setTab("owner-account"); setMobileMenu(false);',
        'className="avatar-button" onClick={() => setTab("owner-account")} aria-label="Open owner account"',
        'function OwnerAccountView(',
        '<h1>Owner Account</h1>',
        '<strong>DOOMSDAY · Independent staging</strong>',
        'onClick={onToggleTheme}',
        'tab === "settings" ? <SettingsView/>',
        'tab === "owner-account" ? <OwnerAccountView userName={userName} theme={theme} onToggleTheme={toggleTheme}/>',
        'className="mobile-back-button"',
        'className={`mobile-home-button ${tab==="dashboard"?"active":""}`}',
        'className="mobile-theme-button"',
        'className="menu-button"',
        'className="bottom-nav"',
        '["dashboard","contracts","customers","estimates","schedule"].includes(id)',
        'window.localStorage.getItem("fire-theme")',
        'window.localStorage.setItem("fire-theme",next)',
        'document.documentElement.dataset.theme=next',
        'const appreciationCents=appreciation?Math.round(subtotal*0.05):0;',
        'const maxPercent=appreciation?45:50;',
        'const total=subtotal>0?Math.max(15000,subtotal-requestedDiscount):0;',
        'deposit:Math.round(total/2)',
        '5% First Responder & Military',
        '% Percentage',
        '$ Dollar amount',
        'The $150 minimum job charge is applied automatically.',
        '50% deposit to schedule',
        'Add another service',
        'Customer profile',
        'Jobs / estimates',
        'Open balance',
        'Continue current job',
        '>Estimates <b>{customerEstimates.length}</b>',
        '>Payments</button>',
        '>Invoices</button>',
        '>Photos <b>{customerPhotos.length}</b>',
        '>Messages <b>{customerMessages.length}</b>',
        '>Notes <b>{customerNotes.length}</b>',
        '<div className="record-empty"><CreditCard /><strong>No payments recorded</strong>',
        'Open an estimate and choose Record payment after receiving money through Wave, Cash App, Venmo, cash, check, card, or bank transfer.',
        '<div className="record-empty"><Receipt /><strong>No invoices yet</strong>',
        'Open an estimate and tap Create invoice.',
        'function CustomerPhotos(',
        '<div className="photo-panel">',
        '<div className="photo-toolbar">',
        '<Label>Photo type</Label>',
        '<SelectItem value="before">Before</SelectItem>',
        '<SelectItem value="after">After</SelectItem>',
        '<SelectItem value="property">Property / damage</SelectItem>',
        '<Label htmlFor="photoCaption">Optional note</Label>',
        'North siding, cracked outlet cover…',
        'Uploading…":"Camera"',
        '<Images className="h-4 w-4"/>Photo library',
        'capture="environment"',
        '<div className="record-empty"><Camera/><strong>No property photos yet</strong>',
        'Choose Before, After, or Property / damage, then use your camera or photo library.',
        '{key:"draft",label:"New quotes"',
        '{key:"sent",label:"Follow up"',
        '{key:"approved",label:"Approved"',
        '{key:"scheduled",label:"Scheduled"',
        '{key:"completed",label:"Completed"',
        '{key:"paid",label:"Paid"',
        '{key:"declined",label:"Lost"',
        '<h2>Needs attention</h2>',
        '<h2>Upcoming jobs</h2>',
        'Number(invoice.pendingRefundCount)>0?"Refund processing":Number(invoice.paymentOverageOpen)>0?"Payment review":statusLabel(invoice.status)',
        'Number(invoice.pendingRefundCount)>0?"Refund pending":Number(invoice.paymentOverageOpen)>0?"Billing exception open"',
        'estimate.status==="approved"?"Next: choose the job date and save it."',
        'estimate.status==="scheduled"?"Next: capture before photos, complete the job report, then create the invoice."',
        'estimate.invoiceId ? "Invoice created" : estimate.status === "completed" ? "Create invoice" : "Complete job first"',
        'initialTemplate={estimate.invoiceId?"invoice":"estimate"}',
        'triggerLabel={estimate.invoiceId?"Send invoice":"Send estimate"}',
        'disabled={saving || Boolean(estimate.invoiceId) || estimate.status !== "completed"}',
        'const resolvedBillingTotalCents =',
        'estimate.invoiceTotalCents ?? estimate.totalCents',
        'Number(estimate.paymentOverageOpen)===0',
        'Number(estimate.pendingRefundCount)===0',
        'initialTemplate="review"',
    ],
    Path('app/estimate/[token]/page.tsx'): [
        '<p>ESTIMATE FOR</p>',
        '<small>Estimate total</small>',
        '<small>50% deposit</small>',
        '<AcceptEstimateButton',
        'Approve and sign the estimate first. After approval, the 50% deposit reserves your place on the schedule.',
        'After approval, Kyle will contact you to schedule the job and arrange the 50% deposit.',
        '<CustomerPortalNav/>',
        'const billingTotalCents=Number(row.invoiceTotalCents??row.totalCents);',
        'const canPayBalance=billingStateSafe&&!paymentReviewPending&&row.status==="completed"&&balance>0;',
        'Payment received — account review in progress.',
        'Refund processing.',
    ],
    Path('app/pay/[id]/page.tsx'): [
        'pendingRefundCount:number',
        "status='pending'",
        'const paymentReviewPending = Number(row.paymentOverageOpen??0)>0||Number(row.pendingRefundCount??0)>0;',
        'const paymentType: "deposit"|"balance" = row.status==="completed"?"balance":"deposit";',
        'const dueNow = paymentType==="deposit"?depositRemaining:balance;',
        'const canPay = dueNow>0&&approved&&!paymentReviewPending&&(paymentType==="deposit"||row.status==="completed");',
        'After approval, the 50% deposit reserves your place on the schedule. The remaining balance is due upon completion of the work.',
        'Refund processing.',
        'Payment received — account review in progress.',
        'This job is paid in full.',
        '<CustomerPortalNav/>',
    ],
    Path('app/invoice/[token]/page.tsx'): [
        '<p>INVOICE FOR</p>',
        '<small>Invoice total</small>',
        '<small>Balance due</small>',
        'Other Payment Options',
        'Cash App</strong>',
        'Venmo</strong>',
        '{handles.cashApp}',
        '{handles.venmo}',
        '<CustomerPortalNav/>',
        'Payment received — account review in progress',
        'Refund processing',
    ],
    Path('app/customer-portal-nav.tsx'): [
        'export function CustomerPortalNav()',
        'return null;',
    ],
    Path('app/api/estimates/[id]/route.ts'): [
        'if(!existing.acceptedAt||!existing.signedAt)',
        'Only an approved estimate can be scheduled.',
        'Choose a job date and time before marking this estimate scheduled.',
        'Keep the accepted estimate unchanged and make any final service or price changes on the invoice.',
        'const deposit=Math.round(total/2);',
        'const total=Math.max(15000,subtotal-requestedDiscount);',
    ],
    Path('app/api/payments/route.ts'): [
        'estimate.status === "completed"',
        '["approved","scheduled"].includes(estimate.status)',
        'Number(estimate.depositCents)',
        'Number(estimate.totalCents)',
        "type='payment_overage' AND resolved_at IS NULL",
        "status='pending' LIMIT 1",
        'INSERT INTO payments',
        'WHERE ? <= (',
        'The amount due changed while this payment was being recorded.',
        'const refreshed = await env.DB.prepare',
    ],
    Path('app/api/invoices/route.ts'): [
        'Mark the job completed before creating the final invoice.',
        'SELECT id,customer_id AS customerId,share_token AS shareToken FROM invoices WHERE estimate_id=? LIMIT 1',
        'INSERT INTO invoice_items',
        'const invoiceStatus = paidCents >= estimateTotalCents ? "paid" : paidCents > 0 ? "partial" : "draft";',
    ],
    Path('app/api/invoices/[id]/route.ts'): [
        'INSERT INTO invoice_revisions',
        'Invoice total cannot be lower than payments already recorded.',
        'expireOpenCheckoutSessions(existing.estimateId)',
        'A refund is currently processing for this job. Wait for it to finish before editing the final invoice.',
        'existing.status==="sent"||Boolean(existing.firstViewedAt)?"sent":"draft"',
    ],
    Path('app/api/payments/refund/route.ts'): [
        "CASE WHEN ?='Tip' THEN 'Tip Refund' ELSE 'Refund' END,?,'paid'",
        'refundPaymentProvider=`refund:${row.paymentId}:${row.id}`',
        'idempotency-key',
        'fire-refund-${requestId}',
        'externalRefundConfirmed',
        'send the money back first and confirm the external refund before FIRE records it.',
        "status='succeeded'",
    ],
    Path('app/api/message-templates/route.ts'): [
        'if(body.reset)',
        'DELETE FROM message_templates WHERE key=?',
        'ON CONFLICT(key) DO UPDATE SET subject=excluded.subject,body=excluded.body,updated_at=excluded.updated_at',
        'Template message cannot be empty.',
    ],
    Path('app/globals.css'): [
        'FIRE_DR_TEMPLATE_MOBILE_PARITY',
        'FIRE_DR_STANDALONE_TOPBAR_PARITY_V14',
        'position: fixed !important;',
        'padding-top: calc(156px + env(safe-area-inset-top)) !important;',
        'height: calc(148px + env(safe-area-inset-top)) !important;',
        '.topbar .search-box {',
        'bottom: 12px !important;',
        'display: flex !important;',
        'background-color: #fff !important;',
        'backdrop-filter: none !important;',
        '-webkit-backdrop-filter: none !important;',
        'will-change: auto !important;',
        'transform: none !important;',
        '-webkit-transform: none !important;',
    ],
}

missing = []
for path, needles in checks.items():
    if not path.exists():
        missing.append(f'{path}: missing file')
        continue
    text = path.read_text()
    for needle in needles:
        if needle not in text:
            missing.append(f'{path}: missing expected LIVE parity content: {needle}')

if missing:
    print('DR_LIVE_PARITY_OVERLAY_GUARD=FAIL')
    for item in missing:
        print(f'- {item}')
    raise SystemExit(1)

print('DR_LIVE_PARITY_OVERLAY_GUARD=PASS')
print('Protected: crisp fixed opaque standalone top shell with explicit search row and content clearance; owner nav/mobile controls/theme; estimate pricing/discount/minimum/deposit rules; LIVE-captured customer Payments/Invoices/Photos states; scheduling/deposit behavior; completion-to-invoice transition; Templates; customer estimate/payment/invoice portals including pending-refund and unresolved-overpayment payment suppression; accepted-estimate freeze; invoice editing/revisions; payment/refund safeguards; review suppression; customer portals without owner-only navigation.')
print('General scroll/smoothness behavior is intentionally not modified or pinned by this guard.')
