import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';

const LIVE=process.env.FIRE_LIVE_URL||'https://fire-field-calculator-fir.kylebrooks8605.chatgpt.site';
const STAGING=process.env.FIRE_STAGING_URL||'http://127.0.0.1:4173/calculator/';
const OUT=process.env.FIRE_VISUAL_OUT||'calculator/visual-parity';
fs.mkdirSync(OUT,{recursive:true});

const states=[
  {name:'01-sh-mix',top:'SH Mix',views:['#view-mix','#mix'],signature:'Final SH strength'},
  {name:'02-equipment',top:'Equipment',views:['#view-delivery','#view-equipment','#equipment'],signature:'X-Jet'},
  {name:'03-chemicals',top:'Chemicals',views:['#view-chemicals','#chemicals'],signature:'Ettore'},
  {name:'04-chemical-index',top:'Chemical Index',views:['#view-index','#index'],signature:'Chemical Use Index'},
  {name:'05-job-math',top:'Job Math',views:['#view-job','#job'],signature:'Price the whole job'},
  {name:'06-field-guide',top:'Field Guide',views:['#view-guide','#guide'],signature:'Quick safety order'},
  {name:'07-tools',top:'Field Tools',views:['#view-tools','#tools'],signature:'Chemical Inventory'}
];

async function clickText(page,text){const exact=page.getByText(text,{exact:true});for(let i=0;i<await exact.count();i++){const el=exact.nth(i);if(await el.isVisible()){await el.evaluate(node=>node.click());return true}}return false}
async function visibleSelector(page,state){for(const selector of state.views){const loc=page.locator(selector);if(await loc.count()&&await loc.first().isVisible())return selector}const candidates=page.locator('[id^="view-"],#mix,#equipment,#chemicals,#index,#job,#tools,#guide');for(let i=0;i<await candidates.count();i++){const el=candidates.nth(i);if(!await el.isVisible())continue;const text=(await el.innerText()).replace(/\s+/g,' ');if(text.includes(state.signature)){const id=await el.getAttribute('id');if(id)return '#'+id}}return null}
async function activateRoute(page,state){for(let attempt=0;attempt<6;attempt++){await clickText(page,state.top).catch(()=>false);for(let poll=0;poll<14;poll++){await page.waitForTimeout(100);const selector=await visibleSelector(page,state);if(selector){await page.waitForTimeout(180);return selector}}}return null}
async function normalize(page){await page.addStyleTag({content:'*,*::before,*::after{caret-color:transparent!important;animation:none!important;transition:none!important}html{scroll-behavior:auto!important}'})}
async function auditRoute(page,selector){return page.locator(selector).first().evaluate((root,routeSelector)=>{const clean=s=>(s||'').replace(/\s+/g,' ').trim();const controls=[...root.querySelectorAll('input,select,textarea')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0}).map(e=>({tag:e.tagName.toLowerCase(),id:e.id||null,type:e.type||null,value:e.value,label:clean(e.closest('.field')?.querySelector('label')?.textContent||document.querySelector(`label[for="${e.id}"]`)?.textContent||e.getAttribute('aria-label')||''),placeholder:e.getAttribute('placeholder')||null,inputMode:e.getAttribute('inputmode')||null,min:e.getAttribute('min')||null,max:e.getAttribute('max')||null,step:e.getAttribute('step')||null,pattern:e.getAttribute('pattern')||null,autocomplete:e.getAttribute('autocomplete')||null,rowText:clean(e.closest('.pricegrid,.field,.listrow')?.innerText||''),dataRateId:e.getAttribute('data-rate-id')||null}));const buttons=[...root.querySelectorAll('button')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0}).map(e=>({id:e.id||null,text:clean(e.textContent),class:e.className||null}));const cards=[...root.querySelectorAll('.card')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0}).map((c,i)=>({index:i,kicker:clean(c.querySelector('.kicker,.eyebrow')?.textContent),heading:clean(c.querySelector('h2,h3')?.textContent),text:clean(c.innerText)}));return {selector:routeSelector,innerText:clean(root.innerText),controls,buttons,cards}},selector)}
async function themeSignature(page){return page.evaluate(()=>({bodyClass:document.body.className,bg:getComputedStyle(document.body).backgroundColor,color:getComputedStyle(document.body).color}))}
async function enableDark(page,label){const before=await themeSignature(page);let clicked=false;const labelled=page.getByLabel(/dark mode/i);for(let i=0;i<await labelled.count();i++){const el=labelled.nth(i);if(await el.isVisible()){await el.evaluate(node=>node.click());clicked=true;break}}if(!clicked){const byId=page.locator('#themeBtn');if(await byId.count()&&await byId.first().isVisible()){await byId.first().evaluate(node=>node.click());clicked=true}}if(!clicked){const buttons=page.locator('button');for(let i=0;i<await buttons.count();i++){const el=buttons.nth(i);if(!await el.isVisible())continue;const t=((await el.textContent())||'').trim();if(['☾','☀','🌙','☀️'].includes(t)){await el.evaluate(node=>node.click());clicked=true;break}}}if(!clicked)throw new Error(`${label}: dark-mode control not found`);await page.waitForTimeout(260);const after=await themeSignature(page);if(before.bodyClass===after.bodyClass&&before.bg===after.bg&&before.color===after.color)throw new Error(`${label}: dark-mode control did not visibly change theme`);return {before,after}}
async function captureThemeRoutes(page,label,theme,audit){for(const state of states){const selector=await activateRoute(page,state);if(!selector)throw new Error(`${label}: ${theme} ${state.top} did not expose a route containing ${state.signature}`);audit[`${theme}-${state.name}`]=await auditRoute(page,selector);await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(80);await page.screenshot({path:path.join(OUT,`${label}-${theme}-${state.name}.png`),fullPage:true})}}
async function settle(page,base){await page.goto(base,{waitUntil:'commit',timeout:12000});await page.waitForLoadState('domcontentloaded',{timeout:5000}).catch(()=>{});for(let i=0;i<28;i++){if(await page.locator('.tabs,.tabswrap').count()){await page.waitForTimeout(1450);return}await page.waitForTimeout(100)}throw new Error('Calculator navigation did not mount')}
async function capture(base,label,browser){const ctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const page=await ctx.newPage(),audit={};await settle(page,base);await normalize(page);await page.waitForTimeout(120);await page.screenshot({path:path.join(OUT,`${label}-light-00-launch.png`),fullPage:true});await captureThemeRoutes(page,label,'light',audit);audit.themeTransition=await enableDark(page,label);if(!await clickText(page,'SH Mix'))throw new Error(`${label}: could not return to SH Mix for dark launch`);await page.waitForTimeout(220);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(OUT,`${label}-dark-00-launch.png`),fullPage:true});await captureThemeRoutes(page,label,'dark',audit);fs.writeFileSync(path.join(OUT,`${label}-dom-audit.json`),JSON.stringify(audit,null,2));await ctx.close()}

const browser=await chromium.launch({headless:true});try{await capture(LIVE,'live',browser);await capture(STAGING,'staging',browser)}finally{await browser.close()}
const manifest={generated_at:new Date().toISOString(),live:LIVE,staging:STAGING,viewport:{width:390,height:844,deviceScaleFactor:1},themes:['light','dark'],states:['00-launch',...states.map(s=>s.name)],status:'PAIRED_LIGHT_AND_DARK_SCREENSHOTS_AND_DOM_AUDIT_CREATED_NOT_AUTOMATICALLY_CERTIFIED',rule:'Human/pixel and state review is required before VERIFIED IDENTICAL.'};fs.writeFileSync(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,2));console.log(`Created paired light/dark FIRE screenshots and DOM audits in ${OUT}`);
